### ISSUE TITLE
Listing threats in individual files

### ISSUE THREAD

**Issue by msaindane** [owasp-cloud-security/owasp-cloud-security#7]
The *_threats.yaml file can grow large pretty quickly if all the threats are listed in a single YAML file. One suggestion could be splitting each threats in their own unique YAML file.

This would require a change to the threatmodel.md generation script. To simplify this, a naming convention could be used.

One sample naming convention could be: <cloud_platform>_<OSCT_id>_threat.yaml
e.g. aws_OCST-1.3.1_threat.yaml

**Comment by zeroXten** [comment]
Good idea. Perhaps a threats folder with the individual files inside?

**Comment by pjbgf** [comment]
Sounds good, given that threats are both vendor and product specific.
As for the feature files, they could potentially be able to mitigate more than one threat, so to avoid duplication it may make sense to be able to do a 1-N relationship there. What do you think?

**Comment by zeroXten** [comment]
The feature files already there have statements like

> Mitigating against OCST-1.2.1

This could easily be a list of different threats. The problem would be where the stories that live in the folder of a particular service (e..g aws/ec2) actually apply more generally to either services or even provides. I guess we'd have to move them out at that point to a more agnostic service or provider folder.

**Comment by adam234** [comment]
I'm not familiar with OCST, but guess that it's some threat or control taxonomy*?

I believe we are better off with a meaningful name in the convention, rather than a pointer, because some people will understand the names and be able to work faster.  It may be that we should use a naming structure from elsewhere to help drive consistency.  Also, to Fraser's point "this could be a list of different threats", I think the answer is to use something like AWS_EC2_Spoofs-Tampers_threat.yaml.

I don't know what to do about the taxonomic problem of most threats are instances of a more generic class, and some demonstrate multiple inheritance.  When teaching, I can ignore that problem.  Can we ignore multiple inheritance here?  (Eg, tampering with USER_ID=fraser in the cookie allows spoofing; treat it as tampering because that's the root action.)

* Seriously, I googled.  First, I typo'd and got the Ontario Society of Cardilology Technologists, then noticed my error, and got a page of results on the Oregon City Swim Team.  Added security to the search, still don't get anything, but a suggestion that i meant OCS security.. I think this strengthens the argument against dependency.

**Comment by pjbgf** [comment]
@zeroXten Agree with your point on threats. Following with @adam234 comment, it may make sense to have types of threat which are agnostic to the vendor/product specific ones, and would potentially leave at the root of the repo somewhere. They would all be linked somehow. 

@adam234 I believe OCST means OWASP Cloud Security Threat.

**Comment by zeroXten** [comment]
@pjbgf Yeah, the idea was always to have something like iaas alongside aws and azure etc. in the root of the repo, for general IaaS threats and stories. I would imagine that either the TM work for AWS and Azure would have to be mature enough to be able to identify general threats, or we'd have to use some general standards (e.g. CSA, PCI) as a starting point for provider-agnostic threats.

@adam234 Yeah, OCST was just a way of referring to threats within the project. I think it's worth continuing the discussion on alternative approaches.

**Comment by zeroXten** [comment]
@adam234 Inside a AWS_EC2_Spoofs-Tampers_threat.yaml file, would you expect to have multiple threats each with some sort of unique ID?

**Comment by adam234** [comment]
@zeroXten I was thinking there might be two sorts of high level files:

AWS_EC2_DoS-via-biz-logic_threat.yaml which would contain the description of a single threat
AWS_EC2_Spoofs-Tampers_threat.yaml would have multiple threats, and as I think about this a bit more, I would think such a file could be a collection of pointers to more generic threats, the specific components* to which they apply, and general and specific mitigations that could be applied.

*By specific components, I mean anything from "an Ubuntu VM on EC2" to "Acme bank retail.20171023.vmi or earlier"

**Comment by msaindane** [comment]
Keeping each single threat in a separate file would simplify the layout and makes things easier to review in the future. We could keep them in a "threats" folder.

OSCT can still be used as a project identifier, but we can always link to other standards in the "references" section.

The directory structure could looks like:
```
aws/
|__s3/
|   |__threats/
|   |   |__ aws_t_osct131_threat.yaml
|   |   |__ aws_i_osct132_threat.yaml
|   |__features/
|   |__tools/
|__ ec2/
```
The naming convention proposed here is <cloud_provider>_<stride>_<osct_id>_threat.yaml

Not sure what advantage does AWS_EC2_Spoofs-Tampers_threat.yaml have which contains multiple threats listed.

Do you agree? Any other suggestions?

**Comment by Joe9345** [comment]
@msaindane If humans are looking at this, there's a cost to having things not human readable, and there's a cost to having to click on 50 files, and then read a small amount of text in each.

**Comment by zeroXten** [comment]
Some further thoughts on this.

# Assumptions
* We have a provider/service directory structure as per @msaindane's comment above
* We have a generic structure alongside the provider/service that is agnostic to the provider. For example iaas/compute would be the generic form of aws/ec2

# Options
1. All threats in one file
2. Multiple threats per file, grouped in some way
3. One file per threat
4. Some combination of 2 and 3

# All threats in one file
## Pros
* Simple, easy to know where to look (just one file)
* Easy to know the next threat id (e.g. OCST-1.2.20) because the latest will be at the bottom of the file
## Cons
* A large number of threats will be hard to maintain

# Multiple threats per file, grouped in some way
## Pros
* Easier to maintain than one large file
* Easy to find related threats
## Cons
* Grouped by what and according to whom?
* What if a threat fits into multiple groups?

# One file per threat
## Pros
* Obvious unit as the threats are relatively independent from each other
* Easy to maintain
## Cons
* Hard to see relationships between threats
* Humans can't just glance at the threats

# Some combination of 2 and 3
## Pros
* Best of both worlds?
## Cons
* Complex, hard to know which file sits where?

So... now some thoughts on the pros and cons of the various options.

* I think it's agreed that we should at least move away from a single large file
* I would probably struggle to decide which threats need to be grouped, and what grouping to be used for files that have multiple related threats. Also, I don't see this project as a taxonomy. It's more of a shopping list of threats. There should be pointers and references to relevant taxonomies, but in my mind this should be a relatively flat list of threats for a given provider and service.
* One threat per file feels right to me, and I think that generating a human-friendly README from the individual YAML files addresses the concern that one cannot just glance at the various threats. For the YAML files you probably don't have to.

**Comment by zeroXten** [comment]
So, how about this?

```
aws/
|__s3/
|   |__threats/
|   |   |__ osct_1_3_1_snake_case_description_1.yaml
|   |   |__ ocst_1_3_2_snake_case_description_2.yaml
|   |__features/
|   |__tools/
|__ ec2/
```
Could easily put together a python script to validate the filenames and content.

**Comment by msaindane** [comment]
Looks good to me. Can you give an example of what would go in the description. We should aim to keep filenames short as well.

**Comment by zeroXten** [comment]
I guess it would be a trimmed down snake_case version of the name. If we had a validation script it could check file length, but for example

`ocst_1_1_1_sensitive_user_data.yaml`

**Comment by msaindane** [comment]
Ok I like the idea. Seems sensible.

**Comment by zeroXten** [comment]
Done, although this will soon be split into threat features.
